"""Contact messages

Revision ID: ee6a02f07efa
Revises: 864424825738
Create Date: 2024-09-29 12:56:08.667018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee6a02f07efa'
down_revision = '864424825738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reading_time', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('external_link', sa.String(length=255), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('features', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('features')
        batch_op.drop_column('image_url')

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('external_link')
        batch_op.drop_column('reading_time')
        batch_op.drop_column('summary')
        batch_op.drop_column('tags')
        batch_op.drop_column('image_url')

    op.drop_table('contact_messages')
    # ### end Alembic commands ###
